image: maven:3.5.0-jdk-8

pipelines:
    default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - cd maven-root/mtsa
          - mvn -B clean compile # -B batch mode makes Maven less verbose
    branches:
      master:
      - step:
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            - cd maven-root/mtsa
            - mvn -B clean install # -B batch mode makes Maven less verbose
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/root/.m2/repository/mtsa/mtsa/1.0-SNAPSHOT/mtsa-1.0-SNAPSHOT.jar"